export const spellList = {
    counterSpell: {
        name: "Counterspell",
        description: "Interrupts the casting of a spell.",
        level: 3,
        school: "Abjuration",
        castingTime: "1 Reaction",
        range: "60 Ft.",
        components: ["V"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
    fireBall: {
        name: "Fireball",
        description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.",
        level: 3,
        damage: {
            dice: "8d6",
            type: "Fire",
        },
        save: {
            type: "Dexterity",
            description: "A creature takes half damage on a successful save.",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "150 Ft.",
        components: ["V", "S", "M"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
    cureWounds: {
        name: "Cure Wounds",
        description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.",
        level: 1,
        healing: {
            dice: "1d8",
            modifier: "Spellcasting Ability Modifier",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Cleric", "Druid", "Bard"],
    },
    ensnaringStrike: {
        name: "Ensnaring Strike",
        description: "The next time you hit a creature with a weapon attack before the spell ends, a writhing mass of thorny vines appears at the point of impact.",
        level: 1,
        damage: {
            dice: "1d6",
            type: "Piercing",
            description: "Deals damage at the start of each of the target's turns if restrained.",
        },
        save: {
            type: "Strength",
            description: "The target must succeed on a Strength saving throw or be restrained.",
        },
        school: "Conjuration",
        castingTime: "1 Bonus Action",
        range: "Self",
        components: ["V", "S", "M"],
        duration: "Concentration, up to 1 minute",
        classes: ["Ranger"],
    },
    huntersMark: {
        name: "Hunter's Mark",
        description: "You choose a creature you can see within range and mystically mark it as your quarry.",
        level: 1,
        damage: {
            dice: "1d6",
            type: "Additional Damage",
            description: "Deals extra damage whenever you hit the target with a weapon attack.",
        },
        school: "Divination",
        castingTime: "1 Bonus Action",
        range: "90 Ft.",
        components: ["V", "S"],
        duration: "Concentration, up to 1 hour",
        classes: ["Ranger"],
    },
    findTraps: {
        name: "Find Traps",
        description: "You sense the presence of any trap within range that is within line of sight.",
        level: 2,
        school: "Divination",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
    },
    passWithoutATrace: {
        name: "Pass Without Trace",
        description: "A veil of shadows and silence radiates from you, masking you and your companions from detection.",
        level: 2,
        school: "Abjuration",
        castingTime: "1 Action",
        range: "Self",
        components: ["V", "S", "M"],
        duration: "Concentration, up to 1 hour",
        classes: ["Ranger", "Druid"],
    },
    rayOfFrost: {
        name: "Ray of Frost",
        description: "A frigid beam of blue-white light streaks toward a creature within range.",
        level: 0,
        damage: {
            dice: "1d8",
            type: "Cold",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "60 Ft.",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
    message: {
        name: "Message",
        description: "You point your finger toward a creature within range and whisper a message.",
        level: 0,
        school: "Transmutation",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S", "M"],
        duration: "1 Round",
        classes: ["Bard", "Sorcerer", "Wizard"],
    },
    dancingLights: {
        name: "Dancing Lights",
        description: "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs.",
        level: 0,
        school: "Evocation",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S", "M"],
        duration: "Concentration, up to 1 minute",
        classes: ["Bard", "Sorcerer", "Wizard"],
    },
    prestidigitation: {
        name: "Prestidigitation",
        description: "This spell is a minor magical trick that novice spellcasters use for practice.",
        level: 0,
        school: "Transmutation",
        castingTime: "1 Action",
        range: "10 Ft.",
        components: ["V", "S"],
        duration: "Up to 1 hour",
        classes: ["Bard", "Sorcerer", "Wizard"],
    },
    detectMagic: {
        name: "Detect Magic",
        description: "For the duration, you sense the presence of magic within 30 feet of you.",
        level: 1,
        school: "Divination",
        castingTime: "1 Action",
        range: "Self",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
        classes: ["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
    },
    shield: {
        name: "Shield",
        description: "An invisible barrier of magical force appears and protects you.",
        level: 1,
        school: "Abjuration",
        castingTime: "1 Reaction",
        range: "Self",
        components: ["V", "S"],
        duration: "1 Round",
        classes: ["Sorcerer", "Wizard"],
    },
    mageArmor: {
        name: "Mage Armor",
        description: "You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.",
        level: 1,
        school: "Abjuration",
        castingTime: "1 Action",
        range: "Touch",
        components: ["V", "S", "M"],
        duration: "8 Hours",
        classes: ["Sorcerer", "Wizard"],
    },
    fireBolt: {
        name: "Fire Bolt",
        description: "You hurl a mote of fire at a creature or object within range.",
        level: 0,
        damage: {
            dice: "1d10",
            type: "Fire",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
    mageHand: {
        name: "Mage Hand",
        description: "A spectral, floating hand appears at a point you choose within range.",
        level: 0,
        school: "Conjuration",
        castingTime: "1 Action",
        range: "30 Ft.",
        components: ["V", "S"],
        duration: "1 Minute",
        classes: ["Sorcerer", "Wizard"],
    },
    magicMissile: {
        name: "Magic Missile",
        description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.",
        level: 1,
        damage: {
            dice: "1d4+1",
            type: "Force",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
    thunderWave: {
        name: "Thunderwave",
        description: "A wave of thunderous force sweeps out from you.",
        level: 1,
        damage: {
            dice: "2d8",
            type: "Thunder",
        },
        save: {
            type: "Constitution",
            description: "A creature takes half damage on a successful save and is not pushed.",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "Self (15-foot cube)",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    },
    detectThoughts: {
        name: "Detect Thoughts",
        description: "You can read the thoughts of certain creatures.",
        level: 2,
        school: "Divination",
        castingTime: "1 Action",
        range: "Self",
        components: ["V", "S", "M"],
        duration: "Concentration, up to 1 minute",
        classes: ["Bard", "Sorcerer", "Wizard"],
    },
    invisibility: {
        name: "Invisibility",
        description: "A creature you touch becomes invisible until the spell ends.",
        level: 2,
        school: "Illusion",
        castingTime: "1 Action",
        range: "Touch",
        components: ["V", "S", "M"],
        duration: "Concentration, up to 1 hour",
        classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    },
    melfsAcidArrow: {
        name: "Melf's Acid Arrow",
        description: "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid.",
        level: 2,
        damage: {
            dice: "4d4",
            type: "Acid",
            description: "Deals 2d4 acid damage at the end of the target's next turn.",
        },
        school: "Evocation",
        castingTime: "1 Action",
        range: "90 Ft.",
        components: ["V", "S", "M"],
        duration: "Instantaneous",
        classes: ["Wizard"],
    },
    mirrorImage: {
        name: "Mirror Image",
        description: "Three illusory duplicates of yourself appear in your space.",
        level: 2,
        school: "Illusion",
        castingTime: "1 Action",
        range: "Self",
        components: ["V", "S"],
        duration: "1 Minute",
        classes: ["Sorcerer", "Wizard"],
    },
    animateDead: {
        name: "Animate Dead",
        description: "This spell creates undead servants.",
        level: 3,
        school: "Necromancy",
        castingTime: "1 Minute",
        range: "10 Ft.",
        components: ["V", "S", "M"],
        duration: "Instantaneous",
        classes: ["Cleric", "Wizard"],
    },
    dispelMagic: {
        name: "Dispel Magic",
        description: "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.",
        level: 3,
        school: "Abjuration",
        castingTime: "1 Action",
        range: "120 Ft.",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    },
    blight: {
        name: "Blight",
        description: "Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it.",
        level: 4,
        damage: {
            dice: "8d8",
            type: "Necrotic",
        },
        save: {
            type: "Constitution",
            description: "A creature takes half damage on a successful save.",
        },
        school: "Necromancy",
        castingTime: "1 Action",
        range: "30 Ft.",
        components: ["V", "S"],
        duration: "Instantaneous",
        classes: ["Druid", "Sorcerer", "Warlock", "Wizard"],
    },
    disintegrate: {
        name: "Disintegrate",
        description: "A thin green ray springs from your pointing finger to a target that you can see within range.",
        level: 6,
        damage: {
            dice: "10d6 + 40",
            type: "Force",
        },
        save: {
            type: "Dexterity",
            description: "A creature takes no damage on a successful save.",
        },
        school: "Transmutation",
        castingTime: "1 Action",
        range: "60 Ft.",
        components: ["V", "S", "M"],
        duration: "Instantaneous",
        classes: ["Sorcerer", "Wizard"],
    },
};